### PR TITLE
Skip creating version for timestamp when ignoring attribute with a Hash

### LINKED ISSUE #1240: Ignore or Skip attributes dynamically is not working
- [x] This is not a usage question, this is a bug report
- [x] This bug can be reproduced with the script I provide below
- [x] This bug can be reproduced in the latest release of the `paper_trail` gem

```ruby
# frozen_string_literal: true

# Use this template to report PaperTrail bugs.
# Please include only the minimum code necessary to reproduce your issue.
require "bundler/inline"

# STEP ONE: What versions are you using?
gem 'paper_trail', '10.3.1'
gem 'rails', '5.2.3'

ActiveRecord::Schema.define do
  # STEP TWO: Define your tables here.
  create_table :users, force: true do |t|
    t.text :first_name, null: false
    t.timestamps null: false
  end

  create_table :versions do |t|
    t.string :item_type, null: false
    t.integer :item_id, null: false
    t.string :event, null: false
    t.string :whodunnit
    t.text :object, limit: 1_073_741_823
    t.text :object_changes, limit: 1_073_741_823
    t.datetime :created_at
  end
  add_index :versions, %i[item_type item_id]
end
ActiveRecord::Base.logger = Logger.new(STDOUT)
require "paper_trail"

# STEP FOUR: Define your AR models here.
class User < ActiveRecord::Base
  has_paper_trail on: %i[update destroy], ignore: { first_name: Proc.new { |obj|  true } }
end

# STEP FIVE: Please write a test that demonstrates your issue.
class BugTest < ActiveSupport::TestCase
  def test_1
    User.create(first_name: "Jane")
    assert_difference(-> { PaperTrail::Version.count },  0) {
      User.update(first_name: "Jane 2")
    }
  end
end

# STEP SIX: Run this script using `ruby my_bug_report.rb`
```

### PR DESCRIPTION
**Pull request by tlynam**
- Resolves #1240
- When a column is ignored via Hash and only that column is updated, it shouldn't create a version for `updated_at`.

Thank you for your contribution!

Check the following boxes:

- [x] Wrote [good commit messages][1].
- [x] Feature branch is up-to-date with `master` (if not - rebase it).
- [x] Squashed related commits together.
- [x] Added tests.
- [x] Added an entry to the [Changelog](../blob/master/CHANGELOG.md) if the new 
  code introduces user-observable changes.
- [x] The PR relates to *only* one subject with a clear title
  and description in grammatically correct, complete sentences.

[1]: http://chris.beams.io/posts/git-commit/

### CODE REVIEW

File: spec/models/gadget_spec.rb [hunk 1]
```diff
@@ -8,12 +8,25 @@
...
+      end
+    end
+
+    context "ignored via Hash" do
+      it "generates a version when the ignored attribute isn't true" do
+        expect { gadget.update_attribute(:color, "Blue") }.to(change { gadget.versions.size }.by(1))
+        expect(gadget.versions.last.changeset.keys).to eq %w[color updated_at]
+      end
+
+      it "doesn't generate a version when the ignored attribute is true" do
```
Comment (tlynam) [inline spec/models/gadget_spec.rb:27]: This test fails.  This should succeed right?

File: spec/models/gadget_spec.rb [hunk 2]
```diff
@@ -8,12 +8,25 @@
...
-    it "generates a version for updates to `name` attribute" do
+    it "generates a version for updates" do
       expect { gadget.update_attribute(:name, "Hammer") }.to(change { gadget.versions.size }.by(1))
     end
 
-    it "ignores for updates to `brand` attribute" do
-      expect { gadget.update_attribute(:brand, "Stanley") }.not_to(change { gadget.versions.size })
+    context "ignored via symbol" do
+      it "doesn't generate a version" do
+        expect { gadget.update_attribute(:brand, "Picard") }.not_to(change { gadget.versions.size })
```
Comment (tlynam) [inline spec/models/gadget_spec.rb:17]: Updated name to `Picard` so the line doesn't exceed the maximum for Rubocop.

File: spec/models/gadget_spec.rb (hunk 1 above)
Comment (tlynam) [reply spec/models/gadget_spec.rb:27]: Hi @jaredbeck, so when using `ignored` with a Hash, it still creates a version for the timestamp.

File: spec/models/gadget_spec.rb (hunk 2 above)
Comment (jaredbeck) [reply spec/models/gadget_spec.rb:17]: That's fine. You can also break long lines like this:

```suggestion
        expect { 
          gadget.update_attribute(:brand, "Stanley") 
        }.not_to(change { gadget.versions.size })
```

File: spec/models/gadget_spec.rb (hunk 1 above)
Comment (jaredbeck) [reply spec/models/gadget_spec.rb:27]: > This test fails. This should succeed right?

Yeah, I think so. Nice test. 👍

File: lib/paper_trail/events/base.rb [hunk 3]
```diff
@@ -148,7 +152,7 @@ def changes_in_latest_version
       #
       # @api private
       def ignored_attr_has_changed?
-        ignored = @record.paper_trail_options[:ignore] + @record.paper_trail_options[:skip]
```
Comment (tlynam) [inline lib/paper_trail/events/base.rb:151]: Here it was only considering ignored attributes defined in the array as symbols and not Hashes.

File: lib/paper_trail/events/base.rb [hunk 4]
```diff
@@ -148,7 +152,7 @@ def changes_in_latest_version
...
+        ignored = calculated_ignored_array + @record.paper_trail_options[:skip]
```
Comment (tlynam) [inline lib/paper_trail/events/base.rb:155]: This ignores when attributes are either defined as symbols or hashes.

File: lib/paper_trail/events/base.rb [hunk 5]
```diff
@@ -107,7 +107,7 @@ def attribute_in_previous_version(attr_name, is_touch)
       end
 
       # @api private
-      def changed_and_not_ignored
+      def calculated_ignored_array
```
Comment (tlynam) [inline lib/paper_trail/events/base.rb:110]: Extracts this calculation to be used by `changed_and_not_ignored` as well as `ignored_attr_has_changed?`

File: spec/models/gadget_spec.rb (hunk 2 above)
Comment (tlynam) [reply spec/models/gadget_spec.rb:17]: Sounds good!

**Comment by tlynam** [comment]
Hi @jaredbeck, hope you're well.  Please let me know if I should go into more detail on this change.
